---
- name: restart sshd
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
  ignore_errors: Yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
